from sqlmodel import Field, SQLModel
from typing import Optional

class QCEWTable(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    trans_code: str
    state_fips: str
    year: int
    qtr: str
    ui_code: str
    rep_uni_id: str
    ein: str
    pre_ui_code: str
    pre_rep_uni_id: str
    suc_ui_code: str
    suc_rep_uni_id: str
    leg_corp_name: str
    trade_name: str
    ui_str_addr_1: str
    ui_str_addr_2: str
    ui_addr_city: str
    ui_addr_state: str
    ui_addr_5_zip: str
    ui_addr_zip_ext: str
    phys_str_addr_1: str
    phys_str_addr_2: str
    phys_addr_city: str
    phys_addr_state: str
    phys_addr_5_zip: str
    phys_addr_zip_ext: str
    mail_str_addr_1: str
    mail_str_addr_2: str
    mail_addr_city: str
    mail_addr_state: str
    mail_addr_5_zip: str
    mail_addr_zip_ext: str
    mail_addr_type: str
    rep_unit_desc: str
    area_code: str
    phone_prefix: str
    phone_suffix: str
    setup_date_year: str
    setup_date_month: str
    setup_date_day: str
    init_liab_year: str
    init_liab_month: str
    init_liab_day: str
    end_liab_year: str
    end_liab_month: str
    end_liab_day: str
    reactivate_date_year: str
    reactivate_date_month: str
    reactivate_date_day: str
    status_code: str
    ces_indicator: str
    ars_resp_code: str
    ars_refile_year: str
    old_country_code: str
    old_own_code: str
    ars_verif_code: str
    old_town_code: str
    max_rep_uni_num: str
    mwr_mail_indicator: str
    old_naics_code: str
    data_source: str
    special_indic_code: str
    agent_code: str
    sic_code: str
    nsta_code: str
    naics_code: str
    own_code: str
    org_type_code: str
    counrty_code: str
    town_code: str
    aux_code: str
    first_month_employment: str
    first_month_employment_indic: str
    second_month_employment: str
    second_month_employment_indic: str
    third_month_employment: str
    third_month_employment_indic: str
    total_wages: str
    total_wages_indic: str
    taxable_wages: str
    contributions_due: str
    type_coverage_code: str
    meei_code: str
    report_change_indic: str
    firt_comment: str
    second_comment: str
    third_comment: str
    narrative_comment: str
    collect_mod_indic: str
    econ_code_change_indic: str
    ui_addr_type: str
    date_pla_change: str
    geo_soft_a: str
    geo_soft_b: str
    match_code: str
    loc_code: str
    latitude: str
    longitude: str
    year_qtr_new_lat_long: str
    place_code: str
    class_code: str
    census_block: str
    census_tract: str
    addr_cont: str
    p_s_part_full_indic: str
    p_s_transfer_year: str
    p_s_transfer_month: str
    p_s_transfer_day: str
    mult_suc: str
    mult_pre: str
    pre_source_code: str
    suc_source_code: str
    first_suppl_pre_suc: str
    second_suppl_pre_suc: str
    ars_third_party_agent: str
    phone_ext: str
    qcew_contact: str
    qcew_contact_title: str
    qcew_contact_email: str
    qcew_contact_fax: str
    qcew_contact_website: str
    future_use: str
def create_qcew(engine):
    SQLModel.metadata.create_all(engine)
