CREATE TABLE IF NOT EXISTS "hactable" (
    SEM_NUM_PAT TEXT,
    SEM_HSEG_SOC TEXT,
    SEM_FORMA_LEGAL TEXT,
    SEM_NOMBRE TEXT,
    SEM_COD_ACTIVOS TEXT,
    SEM_SIC TEXT,
    SEM_INDUSTRIA TEXT,
    SEM_SIC_NEW TEXT,
    SEM_INDUSTRIA_N TEXT,
    NAICS_R02 TEXT,
    SEM_INDUS_R02 TEXT
);
